/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import githubPublish from "../../src/plugins/github-publish/strapi-admin";
import slugifyComponents from "../../src/plugins/slugify-components/strapi-admin";
import autoContent from "../../src/plugins/auto-content/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "github-publish": githubPublish,
    "slugify-components": slugifyComponents,
    "auto-content": autoContent,
  },
});
