/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import email from "@strapi/email/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import githubPublish from "../../src/plugins/github-publish/strapi-admin";
import autoContent from "../../src/plugins/auto-content/strapi-admin";
import ckeditor from "../../src/plugins/ckeditor/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    email: email,
    documentation: documentation,
    "users-permissions": usersPermissions,
    "github-publish": githubPublish,
    "auto-content": autoContent,
    ckeditor: ckeditor,
  },
});
